### ISSUE TITLE
Extra Character in new line 

### ISSUE THREAD

**Issue by arenshaee** [nikoo28/justify-textview-android#4]
Hi.
In All Breakpoint Lines, there is an extra character, Which is a copy of the last character in the previous line.
like the image below:
![screenshot_1529000617](https://user-images.githubusercontent.com/19183640/41430726-17f37d42-7026-11e8-95c0-8dd998367a6a.png)

How fix this ?????

**Comment by nikoo28** [comment]
Hi,

I am no longer looking into this repository. Please feel free to make any changes and create a pull request if you can fix the issue.

Thanks and Regards
Nikhil Lohia
http://www.studyalgorithms.com

**Comment by arenshaee** [comment]
@nikoo28 Hi.ok thanks. But what do you think about it? do you think why this happens??

**Comment by arenshaee** [comment]
Done, Solved. Going for PR :-D
